package waf

import (
	"net/http"
	"net/http/httptest"
	"testing"
)

func TestDetector_Cloudflare(t *testing.T) {
	// Create a mock server that returns Cloudflare headers
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Server", "cloudflare")
		w.Header().Set("CF-RAY", "abc123-IAD")
		http.SetCookie(w, &http.Cookie{Name: "__cf_bm", Value: "test"})
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("<html><body>Hello</body></html>"))
	}))
	defer server.Close()

	detector := NewDetector()
	result, err := detector.Detect(server.URL)

	if err != nil {
		t.Fatalf("Detect failed: %v", err)
	}

	if result.WAFType != WAFCloudflare {
		t.Errorf("Expected WAFCloudflare, got %v", result.WAFType)
	}

	if result.Confidence < 50 {
		t.Errorf("Expected confidence >= 50, got %d", result.Confidence)
	}
}

func TestDetector_Akamai(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Server", "AkamaiGHost")
		w.Header().Set("X-Akamai-Transformed", "9 - 0")
		http.SetCookie(w, &http.Cookie{Name: "_abck", Value: "test"})
		w.WriteHeader(http.StatusOK)
	}))
	defer server.Close()

	detector := NewDetector()
	result, err := detector.Detect(server.URL)

	if err != nil {
		t.Fatalf("Detect failed: %v", err)
	}

	if result.WAFType != WAFAkamai {
		t.Errorf("Expected WAFAkamai, got %v", result.WAFType)
	}
}

func TestDetector_ModSecurity(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Server", "mod_security")
		w.WriteHeader(http.StatusForbidden)
		w.Write([]byte("this error was generated by mod_security"))
	}))
	defer server.Close()

	detector := NewDetector()
	result, err := detector.Detect(server.URL)

	if err != nil {
		t.Fatalf("Detect failed: %v", err)
	}

	if result.WAFType != WAFModSecurity {
		t.Errorf("Expected WAFModSecurity, got %v", result.WAFType)
	}
}

func TestDetector_NoWAF(t *testing.T) {
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Server", "Apache/2.4")
		w.WriteHeader(http.StatusOK)
		w.Write([]byte("<html><body>Hello</body></html>"))
	}))
	defer server.Close()

	detector := NewDetector()
	result, err := detector.Detect(server.URL)

	if err != nil {
		t.Fatalf("Detect failed: %v", err)
	}

	if result.WAFType != WAFUnknown {
		t.Errorf("Expected WAFUnknown, got %v", result.WAFType)
	}

	if result.Confidence > 30 {
		t.Errorf("Expected low confidence for no WAF, got %d", result.Confidence)
	}
}

func TestGetBypassStrategies(t *testing.T) {
	strategies := GetBypassStrategies(WAFCloudflare)
	if len(strategies) == 0 {
		t.Error("Expected bypass strategies for Cloudflare")
	}

	strategies = GetBypassStrategies(WAFUnknown)
	if len(strategies) == 0 {
		t.Error("Expected default bypass strategies for unknown WAF")
	}
}

func TestWAFType_String(t *testing.T) {
	tests := []struct {
		wafType  WAFType
		expected string
	}{
		{WAFCloudflare, "Cloudflare"},
		{WAFAkamai, "Akamai"},
		{WAFImperva, "Imperva/Incapsula"},
		{WAFUnknown, "Unknown WAF"},
	}

	for _, tt := range tests {
		result := tt.wafType.String()
		if result != tt.expected {
			t.Errorf("Expected %s, got %s", tt.expected, result)
		}
	}
}
